// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using landing_page_isis.Infrastructure.Data;

#nullable disable

namespace landingpageisis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708212540_AddCoupleIdToContract")]
    partial class AddCoupleIdToContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("landing_page_isis.core.ApplicationUser.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appointment_date");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("appointment_status");

                    b.Property<Guid?>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PayerCpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payer_cpf");

                    b.Property<string>("PayerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("payer_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("appointment_price");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminder_sent");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("PackageId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.AppointmentPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PayerCpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payer_cpf");

                    b.Property<string>("PayerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("payer_name");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("RemainingAppointments")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_appointments");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("integer")
                        .HasColumnName("total_appointments");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("PatientId");

                    b.ToTable("appointment_packages", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.AppointmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("appointment_records", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acceptance_token");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("ContractDocumentHtml")
                        .HasColumnType("text")
                        .HasColumnName("contract_document_html");

                    b.Property<Guid?>("CoupleId")
                        .HasColumnType("uuid")
                        .HasColumnName("couple_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("InitialAppointments")
                        .HasColumnType("integer")
                        .HasColumnName("initial_appointments");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<decimal?>("PackagePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("package_price");

                    b.Property<DateOnly?>("PatientBirthDate")
                        .HasColumnType("date")
                        .HasColumnName("patient_birth_date");

                    b.Property<string>("PatientCpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("patient_cpf");

                    b.Property<string>("PatientCpfHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("patient_cpf_hash");

                    b.Property<string>("PatientEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("patient_email");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("patient_name");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("patient_phone");

                    b.Property<string>("PatientState")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("patient_state");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<bool>("TermsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("terms_accepted");

                    b.Property<DateTimeOffset?>("TokenGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_generated_at");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AcceptanceToken")
                        .IsUnique()
                        .HasFilter("\"acceptance_token\" IS NOT NULL");

                    b.HasIndex("CoupleId")
                        .IsUnique()
                        .HasFilter("\"couple_id\" IS NOT NULL");

                    b.HasIndex("PackageId");

                    b.HasIndex("PatientCpfHash")
                        .IsUnique()
                        .HasFilter("\"patient_cpf_hash\" IS NOT NULL");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasFilter("\"patient_id\" IS NOT NULL");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Couple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("Patient1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient1_id");

                    b.Property<Guid>("Patient2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("patient2_id");

                    b.Property<string>("PayerCpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payer_cpf");

                    b.Property<string>("PayerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("payer_name");

                    b.Property<bool>("PolicySigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("policy_signed");

                    b.HasKey("Id");

                    b.HasIndex("Patient1Id");

                    b.HasIndex("Patient2Id");

                    b.ToTable("couples", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Created")
                        .HasColumnType("date")
                        .HasColumnName("lead_created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("lead_email");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("lead_intent");

                    b.Property<string>("LeadStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lead_status");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("lead_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("lead_phone");

                    b.Property<bool>("PolicySigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("policy_signed");

                    b.HasKey("Id");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cpf");

                    b.Property<string>("CpfHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cpf_hash");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PayerCpf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payer_cpf");

                    b.Property<string>("PayerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("payer_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phone");

                    b.Property<bool>("PolicySigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("policy_signed");

                    b.Property<string>("StateOfResidency")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_of_residency");

                    b.HasKey("Id");

                    b.HasIndex("CpfHash")
                        .IsUnique()
                        .HasFilter("\"cpf_hash\" IS NOT NULL");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Appointment", b =>
                {
                    b.HasOne("landing_page_isis.core.Models.Couple", "Couple")
                        .WithMany("Appointments")
                        .HasForeignKey("CoupleId");

                    b.HasOne("landing_page_isis.core.Models.AppointmentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("landing_page_isis.core.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId");

                    b.Navigation("Couple");

                    b.Navigation("Package");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.AppointmentPackage", b =>
                {
                    b.HasOne("landing_page_isis.core.Models.Couple", "Couple")
                        .WithMany("Packages")
                        .HasForeignKey("CoupleId");

                    b.HasOne("landing_page_isis.core.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Couple");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.AppointmentRecord", b =>
                {
                    b.HasOne("landing_page_isis.core.Models.Appointment", "Appointment")
                        .WithOne("Record")
                        .HasForeignKey("landing_page_isis.core.Models.AppointmentRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Contract", b =>
                {
                    b.HasOne("landing_page_isis.core.Models.Couple", "Couple")
                        .WithOne("Contract")
                        .HasForeignKey("landing_page_isis.core.Models.Contract", "CoupleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("landing_page_isis.core.Models.AppointmentPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("landing_page_isis.core.Models.Patient", "Patient")
                        .WithOne("Contract")
                        .HasForeignKey("landing_page_isis.core.Models.Contract", "PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Couple");

                    b.Navigation("Package");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Couple", b =>
                {
                    b.HasOne("landing_page_isis.core.Models.Patient", "Patient1")
                        .WithMany()
                        .HasForeignKey("Patient1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("landing_page_isis.core.Models.Patient", "Patient2")
                        .WithMany()
                        .HasForeignKey("Patient2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient1");

                    b.Navigation("Patient2");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Appointment", b =>
                {
                    b.Navigation("Record");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Couple", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Contract");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("landing_page_isis.core.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
